---
application:
  name: "tgvc-userbot"
  project: "voicechat05"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "vouchat05"
  version: "4.4"
routers:
- name: "main-tgvc-userbot"
  routes:
  - application_name: "tgvc-userbot"
    paths:
    - "/*"
